dependencies:
    - python=3.7
    - pip
    - numpy
    - scipy
    - scikit-learn
    - jupyter
    - requests
    - pandas
    - seaborn
    - click
    - openpyxl
    - pip:
          - watermark
          - pytest
